### ISSUE TITLE
jpserver is not working on python 2.7.12

### ISSUE THREAD

**Issue by gauravmisra24** [johnhuang-cn/jpserve#2]
in jpserve.py code, at line number 38, replace socketserver with SocketServer. Also, at line number 204, replace, ThreadingTCPServer.__init__(self, server_address, RequestHandlerClass) with, 
ForkingTCPServer.__init__(self, server_address, RequestHandlerClass)

**Comment by johnhuang-cn** [comment]
Thank you, it is because I just designed for 3.x at the beginning :)
I'm not familiar with python 2.x
